---
- name: Deploy RKE2 Kubernetes Worker Node
  hosts: workers
  vars_files:
    - vars.yml
  tasks:
    - name: Include common setup tasks
      include_tasks: common-tasks.yml

    - name: Read RKE2 node token from local file
      slurp:
        src: rke2_node_token.txt
      delegate_to: localhost
      register: slurp_rke2_token
      become: no

    - name: Create RKE2 config.yaml for worker node
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          server: "https://{{ apiserver_advertise_address }}:9345"
          token: "{{ slurp_rke2_token['content'] | b64decode | trim }}"
      become: yes

    - name: Install RKE2 Agent
      environment:
        INSTALL_RKE2_TYPE: agent
        INSTALL_RKE2_CHANNEL: "{{ rke2_channel }}"
      command: /usr/local/bin/rke2-install.sh
      args:
        creates: /etc/systemd/system/rke2-agent.service
      become: yes

    - name: Enable and start rke2-agent service
      systemd:
        name: rke2-agent
        daemon_reload: yes
        enabled: yes
        state: started
      become: yes
